### PR TITLE
Add JWT support

### PR DESCRIPTION
**Pull request by m-kad**
Add JWT autentication 
#16

### CODE REVIEW

**Comment by niosega** [comment]
Hi !

First of all, thank you for your pull request. We were going to start working on JWT authentification.

I tried your implementation but I am not able to enable the plugin. I receive error from mattermost. You can find the log here: [https://pastebin.com/7b4RtZzx](https://pastebin.com/7b4RtZzx)

Have you already experienced something similar ?

**Comment by seansackowitz** [comment]
Overall, this looks good to me, and I am able to build, and install/test all non JWT functionality, as I do not have JWT set up on my jitsi server. @niosega I was able to build this by pulling down his branch, merging my master branch into his, to bring in the Dockerfile changes, and from there, run the `./docker-make dist` Could you give that a try and let me know how that goes? Thanks.

**Comment by m-kad** [comment]
Thanks for testing
@niosega What mattermost server version are you using? Can you build this plugin without my patch?

**Comment by niosega** [comment]
@seansackowitz I build the plugin with your technique and now it works ! I tested it on my jitsi server with JWT authentification.

@m-kad The jitsi usernames of participants are not populated with Mattermost username. Is this not implemented ?

Otherwise, the authentification part is working properly ! Thanks a lot :)

**Comment by m-kad** [comment]
No, not at the moment Mattermost usernames are not sent to Jitsi, because, it's hard to know who clicks on the link at the backend, where the link is generated.

I think it's possible but then the token generation or at least raw json part must move to React side. 

That means a bit more communication between React and Go. Maybe in the future.

**Comment by seansackowitz** [comment]
Thanks @m-kad for the work!
Thanks @niosega for testing!

**Pull request merged**
